// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izqiblnmzlzwtybnixxi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6cWlibG5temx6d3R5Ym5peHhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNzc0OTEsImV4cCI6MjA1OTc1MzQ5MX0.nvITBzVao0XGXBXDsRQRYlV5HHVCAcsTLJhIV1mUyAI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);